#!/usr/bin/env bash

set -euo pipefail


src="$1"
shift
parameters=("$@")
runable=$(mktemp)
g++ -Wall -g -o $runable --std=c++14 "$src"
$runable "${parameters:-}"

if [[ -z "${DEV:-}" ]]; then
  rm $runable
  #echo "Set env variable DEV=1 to save binary, "
else
  echo "Binary is $runable"
fi
